Vagrant.configure(2) do |config|
 config.vm.define :chefnode1 do |chefnode1|
 	chefnode1.vm.box = "bento/centos-6.7"
	chefnode1.vm.hostname = "chefnode1"
	chefnode1.vm.network "private_network", ip:"10.20.30.120"
 
 config.vm.provider "virtualbox" do |v|
     v.memory = 512
     v.cpus = 2
  end
 end
end
