Vagrant.configure(2) do |config|
 config.vm.define :chefserver do |chefserver|
 	chefserver.vm.box = "bento/centos-6.7"
	chefserver.vm.hostname = "chefserver"
	chefserver.vm.network "private_network", ip:"10.20.30.100"
	 config.vm.provider "virtualbox" do |v|
		 v.memory = 1024
	         v.cpus = 2
	end

 end
end
